language: node_js
node_js:
   - "14"
   - "13"
   - "12"
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
install:
  - npm install
  - npm install codecov -g
before_script:
  - make
script:
  - npm test
after_success:
  - codecov
jobs:
  include:
    - name: RabbitMQ speed test
      before_script:
        - npm run rabbitmq build
        - npm run rabbitmq start
      script:
        - BROKER=rabbitmq npx ts-node test/client/speedtest.ts
    - name: ActiveMQ speed test
      before_script:
        - npm run activemq build
        - npm run activemq start
      script:
        - BROKER=activemq npx ts-node test/client/speedtest.ts
deploy:
  provider: script
  skip_cleanup: true
  script: make publish
  on:
    tags: true
